name: Build Windows Only

on:
  workflow_dispatch:

jobs:
  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "windows-headless"

  build-for-windows-flutter:
    needs: build-RustDeskTempTopMostWindow
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "windows-headless"
